// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Rest from "./Rest.res.mjs";
import * as JSONSchema from "rescript-json-schema/src/JSONSchema.res.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as S$RescriptSchema from "rescript-schema/src/S.res.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function route(app, restRoute, fn) {
  app.register((app, param, done) => {
    let params = Rest.params(restRoute);
    let outputSchema = params.outputSchema;
    let inputSchema = params.inputSchema;
    let pathItems = params.pathItems;
    let url = "";
    for (let idx = 0, idx_finish = pathItems.length; idx < idx_finish; ++idx) {
      let pathItem = pathItems[idx];
      url = typeof pathItem === "string" ? url + pathItem : url + ":" + pathItem.name;
    }
    let routeSchemaResponses = {};
    params.responses.forEach(r => {
      let status = r.status;
      let status$1 = status !== undefined ? status : "default";
      let content = {};
      let jsonSchema = JSONSchema.make(r.dataSchema);
      let tmp;
      tmp = jsonSchema.TAG === "Ok" ? jsonSchema._0 : Stdlib_JsError.throwWithMessage(`Failed to create JSON-Schema for response with status ` + status$1 + `. Error: ` + jsonSchema._0);
      content["application/json"] = {
        schema: tmp
      };
      routeSchemaResponses[status$1] = {
        description: r.description,
        content: content
      };
    });
    let routeSchema_description = params.description;
    let routeSchema_summary = params.summary;
    let routeSchema_deprecated = params.deprecated;
    let routeSchema_response = routeSchemaResponses;
    let routeSchema_operationId = params.operationId;
    let routeSchema_tags = params.tags;
    let routeSchema_externalDocs = params.externalDocs;
    let routeSchema = {
      description: routeSchema_description,
      summary: routeSchema_summary,
      deprecated: routeSchema_deprecated,
      response: routeSchema_response,
      operationId: routeSchema_operationId,
      tags: routeSchema_tags,
      externalDocs: routeSchema_externalDocs
    };
    let routeOptions_method = params.method;
    let routeOptions_handler = (request, reply) => {
      let input;
      try {
        input = S$RescriptSchema.parseOrThrow(request, inputSchema);
      } catch (raw_error) {
        let error = Primitive_exceptions.internalToException(raw_error);
        if (error.RE_EXN_ID === S$RescriptSchema.Raised) {
          reply.status(400);
          reply.send({
            statusCode: 400,
            error: "Bad Request",
            message: S$RescriptSchema.$$Error.message(error._1)
          });
          throw 0;
        }
        throw error;
      }
      return fn({
        input: input
      }).then(implementationResult => {
        let data = S$RescriptSchema.reverseConvertOrThrow(implementationResult, outputSchema);
        let headers = data.headers;
        if (headers) {
          reply.headers(headers);
        }
        reply.status((data.status || 200));
        return data.data;
      });
    };
    let routeOptions_schema = routeSchema;
    let routeOptions = {
      method: routeOptions_method,
      url: url,
      handler: routeOptions_handler,
      schema: routeOptions_schema
    };
    if (app.swagger) {
      let addSchemaFor = location => {
        let item = inputSchema.t.fields[location];
        if (item === undefined) {
          return;
        }
        let jsonSchema = JSONSchema.make(item.schema);
        if (jsonSchema.TAG !== "Ok") {
          return Stdlib_JsError.throwWithMessage(`Failed to create JSON-Schema for ` + location + ` of ` + params.method + ` ` + params.path + ` route. Error: ` + jsonSchema._0);
        }
        routeSchema[location] = jsonSchema._0;
      };
      addSchemaFor("body");
      addSchemaFor("headers");
      addSchemaFor("params");
      addSchemaFor("query");
    }
    app.setValidatorCompiler(param => (param => true));
    if (params.isRawBody) {
      app.addContentTypeParser("application/json", {
        parseAs: "string"
      }, (_req, data, done) => done(null, data));
    }
    app.route(routeOptions);
    done();
  });
}

let Swagger = {};

let Scalar = {};

export {
  route,
  Swagger,
  Scalar,
}
/* Rest Not a pure module */
