// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Rest = require("./Rest.res.js");
var S$RescriptSchema = require("rescript-schema/src/S.res.js");

var $$Promise = {};

function route(app, restRoute, handler) {
  var params = Rest.params(restRoute);
  app.route({
        method: params.definition.method,
        url: params.definition.path,
        handler: (function (request, reply) {
            var variables = S$RescriptSchema.parseAnyOrRaiseWith({
                  body: request.body
                }, params.variablesSchema);
            handler(variables).then(function (response) {
                  reply.send(response);
                });
          })
      });
}

exports.$$Promise = $$Promise;
exports.route = route;
/* Rest Not a pure module */
