// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Sury from "sury";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

async function $$default(args) {
  let result = await fetch(args.path, args);
  let contentType = result.headers.get("content-type");
  if (contentType && contentType.includes("application/") && contentType.includes("json")) {
    return {
      data: await result.json(),
      status: result.status,
      headers: result.headers
    };
  } else if (contentType && contentType.includes("text/")) {
    return {
      data: await result.text(),
      status: result.status,
      headers: result.headers
    };
  } else {
    return {
      data: await result.blob(),
      status: result.status,
      headers: result.headers
    };
  }
}

let ApiFetcher = {
  $$default: $$default
};

function register(map, status, builder) {
  if (map[status]) {
    throw new Error(`[rescript-rest] ` + (`Response for the "` + status + `" status registered multiple times`));
  }
  map[status] = builder;
}

function parsePath(_path, pathItems, pathParams) {
  while (true) {
    let path = _path;
    if (path === "") {
      return;
    }
    let paramStartIdx = path.indexOf("{");
    if (paramStartIdx !== -1) {
      let paramEndIdx = path.indexOf("}");
      if (paramEndIdx !== -1) {
        if (paramStartIdx > paramEndIdx) {
          throw new Error(`[rescript-rest] ` + "Path parameter is not enclosed in curly braces");
        }
        let paramName = path.slice(paramStartIdx + 1 | 0, paramEndIdx);
        if (paramName === "") {
          throw new Error(`[rescript-rest] ` + "Path parameter name cannot be empty");
        }
        let param = {
          name: paramName
        };
        pathItems.push(path.slice(0, paramStartIdx));
        pathItems.push(param);
        pathParams[paramName] = param;
        _path = path.slice(paramEndIdx + 1 | 0);
        continue;
      }
      throw new Error(`[rescript-rest] ` + "Path contains an unclosed parameter");
    }
    pathItems.push(path);
    return;
  };
}

function carriesOwnLogic(schema) {
  if ((s => s.refiner !== undefined)(schema)) {
    return true;
  } else {
    return Stdlib_Option.isSome(schema.to);
  }
}

function coerceMember(member) {
  return S.to(Sury.any, member, {
    decode: {
      TAG: "Sync",
      _0: value => {
        switch (member.type) {
          case "number" :
            let float = (+value);
            if (Number.isNaN(float)) {
              return value;
            } else {
              return float;
            }
          case "boolean" :
            switch (value) {
              case "false" :
                return false;
              case "true" :
                return true;
              default:
                return value;
            }
          default:
            return value;
        }
      }
    },
    encode: {
      TAG: "Sync",
      _0: prim => prim
    }
  });
}

function coerceSchema(schema) {
  if (schema.type === "anyOf" && !carriesOwnLogic(schema)) {
    return Sury.union(schema.anyOf.map(coerceMember));
  } else {
    return coerceMember(schema);
  }
}

function isNestedFlattenSupported(schema) {
  if (schema.type !== "object") {
    return false;
  }
  if (carriesOwnLogic(schema)) {
    return false;
  }
  let reversed = Sury.reverse(schema);
  if (reversed.type === "object") {
    return !carriesOwnLogic(reversed);
  } else {
    return false;
  }
}

let bearerAuthSchema = S.to(Sury.string, Sury.string, {
  decode: {
    TAG: "Sync",
    _0: string => {
      let match = string.split(" ");
      if (match.length !== 2) {
        return Stdlib_JsError.throwWithMessage("Invalid Bearer token");
      }
      let match$1 = match[0];
      if (match$1 === "Bearer") {
        return match[1];
      } else {
        return Stdlib_JsError.throwWithMessage("Invalid Bearer token");
      }
    }
  },
  encode: {
    TAG: "Sync",
    _0: token => `Bearer ` + token
  }
});

let basicAuthSchema = S.to(Sury.string, Sury.string, {
  decode: {
    TAG: "Sync",
    _0: string => {
      let match = string.split(" ");
      if (match.length !== 2) {
        return Stdlib_JsError.throwWithMessage("Invalid Basic token");
      }
      let match$1 = match[0];
      if (match$1 === "Basic") {
        return match[1];
      } else {
        return Stdlib_JsError.throwWithMessage("Invalid Basic token");
      }
    }
  },
  encode: {
    TAG: "Sync",
    _0: token => `Basic ` + token
  }
});

function params(route) {
  let params$1 = route._rest;
  if (params$1 !== undefined) {
    return params$1;
  }
  let definition = route();
  let params$2;
  if (definition.output) {
    let p = definition.operationId;
    let path = `/` + (
      p !== undefined ? p : route.name
    );
    let inputSchema = Sury.object(s => s.f("body", definition.input));
    inputSchema.additionalItems = "strip";
    inputSchema.noValidation = true;
    let outputSchema = Sury.object(s => s.f("data", definition.output));
    outputSchema.additionalItems = "strip";
    outputSchema.noValidation = true;
    let response_status = 200;
    let response_dataSchema = definition.input;
    let response = {
      status: response_status,
      description: undefined,
      dataSchema: response_dataSchema,
      emptyData: false,
      schema: outputSchema
    };
    let responsesMap = {};
    responsesMap["200"] = response;
    params$2 = {
      method: "POST",
      path: path,
      pathItems: [path],
      inputSchema: inputSchema,
      outputSchema: outputSchema,
      responses: [response],
      responsesMap: responsesMap,
      isRawBody: false,
      summary: definition.summary,
      description: definition.description,
      deprecated: definition.deprecated,
      operationId: definition.operationId,
      tags: definition.tags,
      externalDocs: definition.externalDocs
    };
  } else {
    let pathItems = [];
    let pathParams = {};
    parsePath(definition.path, pathItems, pathParams);
    let isRawBody = false;
    let inputSchema$1 = Sury.object(s => definition.input({
      field: (fieldName, schema) => s.nested("body").f(fieldName, schema),
      body: schema => {
        if (isNestedFlattenSupported(schema)) {
          return s.nested("body").flatten(schema);
        } else {
          return s.f("body", schema);
        }
      },
      rawBody: schema => {
        let isNonStringBased;
        isNonStringBased = schema.type !== "string";
        if (isNonStringBased) {
          throw new Error(`[rescript-rest] ` + "Only string-based schemas are allowed in rawBody");
        }
        ((isRawBody = true));
        return s.f("body", schema);
      },
      header: (fieldName, schema) => s.nested("headers").f(fieldName.toLowerCase(), coerceSchema(schema)),
      query: (fieldName, schema) => s.nested("query").f(fieldName, coerceSchema(schema)),
      param: (fieldName, schema) => {
        if (!pathParams[fieldName]) {
          throw new Error(`[rescript-rest] ` + (`Path parameter "` + fieldName + `" is not defined in the path`));
        }
        return s.nested("params").f(fieldName, coerceSchema(schema));
      },
      auth: auth => {
        let tmp;
        tmp = auth === "Bearer" ? bearerAuthSchema : basicAuthSchema;
        return s.nested("headers").f("authorization", tmp);
      }
    }));
    inputSchema$1.additionalItems = "strip";
    inputSchema$1.noValidation = true;
    let schema = inputSchema$1.properties["headers"];
    if (schema !== undefined) {
      schema.additionalItems = "strip";
      schema.noValidation = true;
    }
    let schema$1 = inputSchema$1.properties["params"];
    if (schema$1 !== undefined) {
      schema$1.noValidation = true;
    }
    let schema$2 = inputSchema$1.properties["query"];
    if (schema$2 !== undefined) {
      schema$2.noValidation = true;
    }
    let responsesMap$1 = {};
    let responses = [];
    definition.responses.forEach(r => {
      let builder = {
        emptyData: true
      };
      let schema = Sury.object(s => {
        let status = status$1 => {
          builder.status = status$1;
          register(responsesMap$1, status$1, builder);
          s.tag("status", status$1);
        };
        let header = (fieldName, schema) => s.nested("headers").f(fieldName.toLowerCase(), coerceSchema(schema));
        let definition = r({
          status: status,
          description: d => {
            builder.description = d;
          },
          data: schema => {
            builder.emptyData = false;
            if (isNestedFlattenSupported(schema)) {
              return s.nested("data").flatten(schema);
            } else {
              return s.f("data", schema);
            }
          },
          field: (fieldName, schema) => {
            builder.emptyData = false;
            return s.nested("data").f(fieldName, schema);
          },
          header: header,
          redirect: schema => {
            status(307);
            return header("location", coerceSchema(schema));
          }
        });
        if (builder.emptyData) {
          s.tag("data", null);
        }
        return definition;
      });
      if (builder.status === undefined) {
        register(responsesMap$1, "default", builder);
      }
      schema.additionalItems = "strip";
      schema.noValidation = true;
      let dataSchema = schema.properties["data"];
      builder.dataSchema = dataSchema;
      let schema$1 = schema.properties["headers"];
      if (schema$1 !== undefined) {
        schema$1.additionalItems = "strip";
        schema$1.noValidation = true;
      }
      builder.schema = schema;
      responses.push(builder);
    });
    if (responses.length === 0) {
      throw new Error(`[rescript-rest] ` + "At least single response should be registered");
    }
    params$2 = {
      method: definition.method,
      path: definition.path,
      pathItems: pathItems,
      inputSchema: inputSchema$1,
      outputSchema: Sury.union(responses.map(r => r.schema)),
      responses: responses,
      responsesMap: responsesMap$1,
      isRawBody: isRawBody,
      summary: definition.summary,
      description: definition.description,
      deprecated: definition.deprecated,
      operationId: definition.operationId,
      tags: definition.tags,
      externalDocs: definition.externalDocs,
      jsonQuery: definition.jsonQuery
    };
  }
  route._rest = params$2;
  return params$2;
}

function tokeniseValue(key, value, append) {
  if (Array.isArray(value)) {
    value.forEach((v, idx) => tokeniseValue(key + `[` + idx.toString() + `]`, v, append));
    return;
  } else if (value === null) {
    return append(key, "");
  } else if (value === (void 0)) {
    return;
  } else if (typeof value === "object") {
    Object.keys(value).forEach(k => tokeniseValue(key + `[` + encodeURIComponent(k) + `]`, value[k], append));
    return;
  } else {
    return append(key, value);
  }
}

function getCompletePath(baseUrl, pathItems, maybeQuery, maybeParams, jsonQueryOpt) {
  let jsonQuery = jsonQueryOpt !== undefined ? jsonQueryOpt : false;
  let path = baseUrl;
  for (let idx = 0, idx_finish = pathItems.length; idx < idx_finish; ++idx) {
    let pathItem = pathItems[idx];
    if (typeof pathItem === "string") {
      path = path + pathItem;
    } else {
      let name = pathItem.name;
      let param = maybeParams && maybeParams[name];
      if (param !== undefined) {
        path = path + param;
      } else {
        throw new Error(`[rescript-rest] ` + (`Path parameter "` + name + `" is not defined in input`));
      }
    }
  }
  if (maybeQuery !== undefined) {
    let queryItems = [];
    let append = (key, value) => {
      queryItems.push(key + "=" + encodeURIComponent(value));
    };
    let queryNames = Object.keys(maybeQuery);
    for (let idx$1 = 0, idx_finish$1 = queryNames.length; idx$1 < idx_finish$1; ++idx$1) {
      let queryName = queryNames[idx$1];
      let value = maybeQuery[queryName];
      let key = encodeURIComponent(queryName);
      if (value !== (void 0)) {
        if (jsonQuery) {
          append(key, typeof value === "string" && value !== "true" && value !== "false" && value !== "null" && Number.isNaN(parseFloat(value)) ? value : JSON.stringify(value));
        } else {
          tokeniseValue(key, value, append);
        }
      }
    }
    if (queryItems.length !== 0) {
      path = path + "?" + queryItems.join("&");
    }
  }
  return path;
}

function url(route, input, baseUrlOpt) {
  let baseUrl = baseUrlOpt !== undefined ? baseUrlOpt : "";
  let match = params(route);
  let data = S.convertOrThrow(input, match.inputSchema, undefined, Sury.unknown);
  return getCompletePath(baseUrl, match.pathItems, data.query, data.params, false);
}

let global = {
  c: undefined
};

function fetch$1(route, input, client) {
  let match = params(route);
  let responsesMap = match.responsesMap;
  let client$1;
  if (client !== undefined) {
    client$1 = client;
  } else {
    let client$2 = global.c;
    if (client$2 !== undefined) {
      client$1 = client$2;
    } else {
      throw new Error(`[rescript-rest] ` + (`Client is not set for the ` + match.path + ` fetch request. Please, use Rest.setGlobalClient or pass a client explicitly to the Rest.fetch arguments`));
    }
  }
  let data = S.convertOrThrow(input, match.inputSchema, undefined, Sury.unknown);
  if (data.body !== (void 0)) {
    if (!match.isRawBody) {
      data.body = (JSON.stringify(data["body"]));
    }
    if (data.headers === (void 0)) {
      data.headers = {};
    }
    data.headers["content-type"] = "application/json";
  }
  return client$1.fetcher({
    body: data.body,
    headers: data.headers,
    method: match.method,
    path: getCompletePath(client$1.baseUrl, match.pathItems, data.query, data.params, match.jsonQuery)
  }).then(fetcherResponse => {
    let responseStatus = fetcherResponse.status;
    let response = responsesMap[responseStatus] || responsesMap[(responseStatus / 100 | 0) + "XX"] || responsesMap["default"];
    if (response !== undefined) {
      try {
        return Sury.parseOrThrow(fetcherResponse, response.schema);
      } catch (raw_error) {
        let error = Primitive_exceptions.internalToException(raw_error);
        if (error.RE_EXN_ID === S.Exn) {
          let error$1 = error._1;
          if (error$1.code === "invalid_input") {
            let input = error$1.input;
            if (input !== undefined && Sury.pathToText(error$1.path) === "data") {
              let message = `Failed parsing response data. Reason: Expected ` + Sury.toInputExpression(error$1.expected) + `, received ` + Primitive_option.valFromOption(input);
              throw new Error(`[rescript-rest] ` + message);
            }
          }
          let message$1 = `Failed parsing response at ` + Sury.pathToText(error$1.path) + `. Reason: ` + error$1.reason;
          throw new Error(`[rescript-rest] ` + message$1);
        }
        throw error;
      }
    } else {
      let error$2 = `Unexpected response status "` + fetcherResponse.status.toString() + `"`;
      if (fetcherResponse.data && typeof fetcherResponse.data.message === "string") {
        error$2 = error$2 + ". Message: " + fetcherResponse.data.message;
      }
      throw new Error(`[rescript-rest] ` + error$2);
    }
  });
}

function client(baseUrl, fetcherOpt) {
  let fetcher = fetcherOpt !== undefined ? fetcherOpt : $$default;
  return {
    baseUrl: baseUrl,
    fetcher: fetcher
  };
}

function setGlobalClient(baseUrl, fetcher) {
  let match = global.c;
  if (match !== undefined) {
    throw new Error(`[rescript-rest] ` + "There's already a global client defined. You can have only one global client at a time.");
  }
  global.c = client(baseUrl, fetcher);
}

let Response = {};

export {
  Response,
  params,
  ApiFetcher,
  url,
  client,
  setGlobalClient,
  fetch$1 as fetch,
}
/* bearerAuthSchema Not a pure module */
