// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Rest from "./Rest.res.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as S$RescriptSchema from "rescript-schema/src/S.res.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function handler(route, implementation) {
  let match = Rest.params(route);
  let isRawBody = match.isRawBody;
  let outputSchema = match.outputSchema;
  let inputSchema = match.inputSchema;
  let path = match.path;
  let method = match.method;
  match.pathItems.forEach(pathItem => {
    if (typeof pathItem === "string") {
      return;
    }
    throw new Error(`[rescript-rest] ` + (`Route ` + path + ` contains a path param ` + pathItem.name + ` which is not supported by Next.js handler yet`));
  });
  return async (req, res) => {
    if (req.method !== method) {
      return res.status(404).end();
    }
    if (req.body === undefined) {
      let rawBody = {
        contents: ""
      };
      await new Promise((resolve, reject) => {
        req.on("data", chunk => {
          rawBody.contents = rawBody.contents + chunk;
        });
        req.on("end", resolve);
        req.on("error", reject);
      });
      req.body = isRawBody ? rawBody.contents : JSON.parse(rawBody.contents);
    } else if (isRawBody) {
      Stdlib_JsError.throwWithMessage("Routes with Raw Body require to disable body parser for your handler. Add `let config: RestNextJs.config = {api: {bodyParser: false}}` to the file with your handler to make it work.");
    }
    let input;
    try {
      input = S$RescriptSchema.parseOrThrow(req, inputSchema);
    } catch (raw_error) {
      let error = Primitive_exceptions.internalToException(raw_error);
      if (error.RE_EXN_ID === S$RescriptSchema.Raised) {
        return res.status(400).json({
          error: S$RescriptSchema.$$Error.message(error._1)
        });
      }
      throw error;
    }
    try {
      let implementationResult = await implementation({
        input: input,
        req: req,
        res: res
      });
      let data = S$RescriptSchema.reverseConvertOrThrow(implementationResult, outputSchema);
      let headers = data.headers;
      if (headers !== undefined) {
        Object.keys(headers).forEach(key => res.setHeader(key, headers[key]));
      }
      return res.status((data.status || 200)).json(data.data);
    } catch (raw_error$1) {
      let error$1 = Primitive_exceptions.internalToException(raw_error$1);
      if (error$1.RE_EXN_ID === S$RescriptSchema.Raised) {
        return Stdlib_JsError.throwWithMessage(`Unexpected error in the ` + path + ` route: ` + S$RescriptSchema.$$Error.message(error$1._1));
      }
      throw error$1;
    }
  };
}

export {
  handler,
}
/* Rest Not a pure module */
