// Generated by ReScript, PLEASE EDIT WITH CARE

import Swr from "swr";
import * as Rest from "./Rest.res.mjs";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function use(route, input, options, client) {
  let match = Rest.params(route);
  if (match.method !== "GET") {
    Stdlib_JsError.throwWithMessage(`[rescript-rest] Only GET requests are supported by Swr`);
  }
  return Swr(input !== undefined ? Rest.url(route, Primitive_option.valFromOption(input), client !== undefined ? client.baseUrl : undefined) : null, param => Rest.fetch(route, Belt_Option.getExn(input), client), options !== undefined ? Primitive_option.valFromOption(options) : undefined);
}

export {
  use,
}
/* swr Not a pure module */
