// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Swr = require("swr").default;
let Rest = require("./Rest.res.js");
let Belt_Option = require("@rescript/runtime/lib/js/Belt_Option.js");
let Stdlib_JsError = require("@rescript/runtime/lib/js/Stdlib_JsError.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");

function use(route, input, options, client) {
  let match = Rest.params(route);
  if (match.method !== "GET") {
    Stdlib_JsError.throwWithMessage(`[rescript-rest] Only GET requests are supported by Swr`);
  }
  return Swr(input !== undefined ? Rest.url(route, Primitive_option.valFromOption(input), client !== undefined ? client.baseUrl : undefined) : null, param => Rest.fetch(route, Belt_Option.getExn(input), client), options !== undefined ? Primitive_option.valFromOption(options) : undefined);
}

exports.use = use;
/* swr Not a pure module */
