// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("ava").default;

Ava("foo", (function (t) {
        var route = function (param) {
          return {
                  method: "GET",
                  path: "/height"
                };
        };
        t.deepEqual(route, route);
      }));

/*  Not a pure module */
